name: Angular Tests

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.1

      - name: Change to Angular project directory
        working-directory: ./nexttech.client
        run: echo "In Angular directory"

      - name: Install dependencies
        working-directory: ./nexttech.client
        run: npm install

      - name: Run Angular tests
        working-directory: ./nexttech.client
        run: npm run test -- --watch=false --browsers=ChromeHeadless