name: C# .NET Tests

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'  # Change to the .NET version you're using

    - name: Install dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build

    - name: Install dependencies
      run: dotnet restore NextTech.Tests
      
    - name: Build the solution
      run: dotnet build NextTech.Tests

    - name: Run Unit Tests
      run: dotnet test NextTech.Tests --filter "FullyQualifiedName~UnitTest"

    - name: Run Integration Tests
      run: dotnet test NextTech.Tests --filter "FullyQualifiedName~IntegrationTest"